postgres: &postgres
  adapter: postgresql
  username: suite101_db
  password: 632bVy6Le3h9f
  encoding: unicode
  host: suite101-psql-staging-master
#  port: 5432

octopus:
  environments:
    - development
    - staging
  development:
    com:
      database: stats_com_dev
      <<: *postgres
    de:
      database: stats_de_dev
      <<: *postgres
    net:
      database: stats_net_dev
      <<: *postgres
    fr:
      database: stats_fr_dev
      <<: *postgres
  staging:
    com:
      database: suite101_com_staging
      <<: *postgres
    de:
      database: suite101_de_staging
      <<: *postgres
    net:
      database: suite101_net_staging
      <<: *postgres
    fr:
      database: suite101_fr_staging
      <<: *postgres
  production:
    com:
      database: stats_com_production
      <<: *postgres
    de:
      database: stats_de_production
      <<: *postgres
    net:
      database: stats_net_production
      <<: *postgres
    fr:
      database: stats_fr_production
      <<: *postgres