postgres: &postgres
  adapter: postgresql
  username: postgres
  password:
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  
octopus:
  octopus_enviroments:
    - development
    - staging
  development:
    shards:
      com:
        database: stats_com_dev
        <<: *postgres
      de:
        database: stats_de_dev
        <<: *postgres
      net:
        database: stats_net_dev
        <<: *postgres
      fr:
        database: stats_fr_dev
        <<: *postgres
  staging:
    shards:
      com:
        database: suite101_com_staging
        <<: *postgres
      de:
        database: suite101_de_staging
        <<: *postgres
      net:
        database: suite101_net_staging
        <<: *postgres
      fr:
        database: suite101_fr_staging
        <<: *postgres